// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpdTRA8y6NXhJucBwDP8Eob9M94nb-Gxo',
    appId: '1:98396868255:web:d783279fd2cbe068659caa',
    messagingSenderId: '98396868255',
    projectId: 'turisagoapp',
    authDomain: 'turisagoapp.firebaseapp.com',
    storageBucket: 'turisagoapp.firebasestorage.app',
    measurementId: 'G-SKGW58B5Z7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYqTtus0bIu6V8p-BQ6db9AHtP3hKHRRI',
    appId: '1:98396868255:android:a9f358d2a1b47f92659caa',
    messagingSenderId: '98396868255',
    projectId: 'turisagoapp',
    storageBucket: 'turisagoapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyJF5tHsRtDfPk-5uJGJ6O79RwrIjRPuc',
    appId: '1:98396868255:ios:99ecf8347ce1e764659caa',
    messagingSenderId: '98396868255',
    projectId: 'turisagoapp',
    storageBucket: 'turisagoapp.firebasestorage.app',
    iosBundleId: 'com.example.turisagoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyJF5tHsRtDfPk-5uJGJ6O79RwrIjRPuc',
    appId: '1:98396868255:ios:99ecf8347ce1e764659caa',
    messagingSenderId: '98396868255',
    projectId: 'turisagoapp',
    storageBucket: 'turisagoapp.firebasestorage.app',
    iosBundleId: 'com.example.turisagoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpdTRA8y6NXhJucBwDP8Eob9M94nb-Gxo',
    appId: '1:98396868255:web:6ca0aa4f59abbef2659caa',
    messagingSenderId: '98396868255',
    projectId: 'turisagoapp',
    authDomain: 'turisagoapp.firebaseapp.com',
    storageBucket: 'turisagoapp.firebasestorage.app',
    measurementId: 'G-6S1GQXE6EK',
  );
}
